
language: python
python:
  - 3.6
  - 3.5

# Python 3.7 currently (early 2019) needs a newer Ubuntu version than the
# default image on Travis.
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt

script:
  - pytest -v --cov=calculator
